name: build
on:
  pull_request

jobs:
 checkov:
    runs-on: ubuntu-latest
    name: bridgecrewio/checkov-action@master
    steps:
     - name : checkout repo
       uses: actions/checkout@master
     - name: Test with Checkov
       id: checkov
       uses: bridgecrewio/checkov-action@master
       with:
          directory: "."
          framework: terraform
          download_external_modules: true 
          log_level: DEBUG
          output_format: sarif
          

          
     
