name: build
on:
  push: 
    branches:    
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout repo
      - name: Run yor action
        uses: bridgecrewio/yor-action@main

