name: checkov
on:
  pull_request

jobs:
 checkov:
    runs-on: ubuntu-latest
    steps:
     - name : checkout repo
       uses: actions/checkout@v2
     - name: Test with Checkov
       id: checkov
       uses: bridgecrewio/checkov-action@master
       with:
          directory: "."
          framework: terraform
          download_external_modules: true 
          #soft_fail: true
          output_format: sarif
          quiet: true
